server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    password: root
    username: root
  redis:
    port: 6379
    database: 0
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /root


