spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1905-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mr.malldemo.entity
server:
  port: 8088